# Hydrogram A and B (Resolução ANA 911-2014) for Belo Monte
# http://arquivos.ana.gov.br/resolucoes/2014/ANALegis/LEGISResolucao911-2014.pdf
# The position of each value indicates the month (0: january, 1: february, ..., 11: december)
hydrogram = {
    'A': [1100, 1600, 2500, 4000, 1800, 1200, 1000, 900, 750, 700, 800, 900],
    'B': [1100, 1600, 4000, 8000, 4000, 2000, 1200, 900, 750, 700, 800, 900],
    'A_B': [1100, 1600, 3250, 6000, 2900, 1600, 1100, 900, 750, 700, 800, 900],
    'IBAMA': [3100, 10900, 14200, 13400, 5200, 1800, 1300, 900, 750, 760, 1000, 1200]
}

hydrogram_used = hydrogram['B']

# Dictionary containing the natural and artificial code for each station
stations_code = {
1: {'name': ['Camargos'], 'id_nat': [1], 'id_art': [None]},
2: {'name': ['Itutinga'], 'id_nat': [2], 'id_art': [None]},
4: {'name': ['Funil-MG'], 'id_nat': [211], 'id_art': [None]},
6: {'name': ['Furnas'], 'id_nat': [6], 'id_art': [None]},
7: {'name': ['Mascarenhas de Moraes'], 'id_nat': [7], 'id_art': [None]},
8: {'name': ['Estreito'], 'id_nat': [8], 'id_art': [None]},
9: {'name': ['Jaguara'], 'id_nat': [9], 'id_art': [None]},
10: {'name': ['Igarapava'], 'id_nat': [10], 'id_art': [None]},
11: {'name': ['Volta Grande'], 'id_nat': [11], 'id_art': [None]},
12: {'name': ['Porto Colômbia'], 'id_nat': [12], 'id_art': [None]},
14: {'name': ['Caconde'], 'id_nat': [14], 'id_art': [None]},
15: {'name': ['Euclides da Cunha'], 'id_nat': [15], 'id_art': [None]},
16: {'name': ['Limoeiro'], 'id_nat': [16], 'id_art': [None]},
17: {'name': ['Marimbondo'], 'id_nat': [17], 'id_art': [None]},
18: {'name': ['Água Vermelha'], 'id_nat': [18], 'id_art': [None]},
20: {'name': ['Batalha'], 'id_nat': [22], 'id_art': [None]},
21: {'name': ['Serra do Facão'], 'id_nat': [251], 'id_art': [None]},
24: {'name': ['Emborcação'], 'id_nat': [24], 'id_art': [None]},
25: {'name': ['Nova Ponte'], 'id_nat': [25], 'id_art': [None]},
26: {'name': ['Miranda'], 'id_nat': [206], 'id_art': [None]},
27: {'name': ['Capim Branco 1'], 'id_nat': [207], 'id_art': [None]},
28: {'name': ['Capim Branco 2'], 'id_nat': [28], 'id_art': [None]},
29: {'name': ['Corumbá IV'], 'id_nat': [205], 'id_art': [None]},
30: {'name': ['Corumbá I'], 'id_nat': [209], 'id_art': [None]},
31: {'name': ['Itumbiara'], 'id_nat': [31], 'id_art': [None]},
32: {'name': ['Cachoeira Dourada'], 'id_nat': [32], 'id_art': [None]},
33: {'name': ['São Simão'], 'id_nat': [33], 'id_art': [None]},
34: {'name': ['Ilha Solteira', 'Ilha Solteira Equivalente'], 'id_nat': [34, 244], 'id_art': [None, 44]},
37: {'name': ['Barra Bonita'], 'id_nat': [237], 'id_art': [37]},
38: {'name': ['Bariri'], 'id_nat': [238], 'id_art': [38]},
39: {'name': ['Ibitinga'], 'id_nat': [239], 'id_art': [39]},
40: {'name': ['Promissão'], 'id_nat': [240], 'id_art': [40]},
42: {'name': ['Nova Avanhandava'], 'id_nat': [242], 'id_art': [42]},
43: {'name': ['Três Irmãos'], 'id_nat': [243], 'id_art': [43]},
45: {'name': ['Jupiá'], 'id_nat': [245], 'id_art': [45]},
46: {'name': ['Porto Primavera'], 'id_nat': [246], 'id_art': [46]},
47: {'name': ['Jurumirim'], 'id_nat': [47], 'id_art': [None]},
48: {'name': ['Piraju'], 'id_nat': [48], 'id_art': [None]},
49: {'name': ['Chavantes'], 'id_nat': [49], 'id_art': [None]},
50: {'name': ['Lucas Nogueira Garcez'], 'id_nat': [50], 'id_art': [None]},
51: {'name': ['Canoas 2'], 'id_nat': [51], 'id_art': [None]},
52: {'name': ['Canoas 1'], 'id_nat': [52], 'id_art': [None]},
54: {'name': ['Santa Branca do Tigagi'], 'id_nat': [54], 'id_art': [None]},
61: {'name': ['Capivara'], 'id_nat': [61], 'id_art': [None]},
62: {'name': ['Taquaruçu'], 'id_nat': [62], 'id_art': [None]},
63: {'name': ['Rosana'], 'id_nat': [63], 'id_art': [None]},
66: {'name': ['Itaipu'], 'id_nat': [266], 'id_art': [66]},
71: {'name': ['Santa Clara PR'], 'id_nat': [71], 'id_art': [None]},
72: {'name': ['Fundão'], 'id_nat': [72], 'id_art': [None]},
73: {'name': ['Jordão'], 'id_nat': [73], 'id_art': [70]},
74: {'name': ['Foz do Areia'], 'id_nat': [74], 'id_art': [None]},
76: {'name': ['Segredo'], 'id_nat': [76], 'id_art': [75]},
77: {'name': ['Salto Santiago'], 'id_nat': [77], 'id_art': [None]},
78: {'name': ['Salto Osório'], 'id_nat': [78], 'id_art': [None]},
82: {'name': ['Salto Caxias'], 'id_nat': [222], 'id_art': [None]},
83: {'name': ['Baixo Iguaçu'], 'id_nat': [81], 'id_art': [None]},
86: {'name': ['Barra Grande'], 'id_nat': [215], 'id_art': [None]},
88: {'name': ['São Roque'], 'id_nat': [88], 'id_art': [None]},
89: {'name': ['Garibaldi'], 'id_nat': [89], 'id_art': [None]},
90: {'name': ['Campos Novos'], 'id_nat': [216], 'id_art': [None]},
91: {'name': ['Machadinho'], 'id_nat': [217], 'id_art': [None]},
92: {'name': ['Itá'], 'id_nat': [92], 'id_art': [None]},
93: {'name': ['Passo Fundo'], 'id_nat': [93], 'id_art': [None]},
94: {'name': ['Monjolinho'], 'id_nat': [220], 'id_art': [None]},
95: {'name': ['Quebra Queixo'], 'id_nat': [286], 'id_art': [None]},
97: {'name': ['Castro Alves'], 'id_nat': [98], 'id_art': [None]},
98: {'name': ['Monte Claro'], 'id_nat': [97], 'id_art': [None]},
99: {'name': ['14 de Julho'], 'id_nat': [284], 'id_art': [None]},
101: {'name': ['São José'], 'id_nat': [102], 'id_art': [None]},
102: {'name': ['Passo São João'], 'id_nat': [103], 'id_art': [None]},
103: {'name': ['Foz Chapecó'], 'id_nat': [94], 'id_art': [None]},
105: {'name': ['Ponte Nova / Alto Tietê'], 'id_nat': [160], 'id_art': [None]},
# 107: {'name': ['Edgard de Souza (c/ tributários)', 'Edgard de Souza (s/ tributários)'], 'id_nat': [161, 164], 'id_art': [None, None]},
107: {'name': ['Edgard de Souza (c/ tributários)'], 'id_nat': [161], 'id_art': [None]},
108: {'name': ['Traição'], 'id_nat': [104], 'id_art': [None]},
109: {'name': ['Pedreira'], 'id_nat': [109], 'id_art': [None]},
110: {'name': ['Ernestina'], 'id_nat': [110], 'id_art': [None]},
111: {'name': ['Passo Real'], 'id_nat': [111], 'id_art': [None]},
112: {'name': ['Jacuí'], 'id_nat': [112], 'id_art': [None]},
113: {'name': ['Itaúba'], 'id_nat': [113], 'id_art': [None]},
114: {'name': ['Dona Francisca'], 'id_nat': [114], 'id_art': [None]},
115: {'name': ['Capivari Cachoeira'], 'id_nat': [115], 'id_art': [None]},
117: {'name': ['Guarapiranga'], 'id_nat': [117], 'id_art': [None]},
118: {'name': ['Billings'], 'id_nat': [118], 'id_art': [None]},
119: {'name': ['Pedras', 'Billings + Pedras', 'Henry Borden'], 'id_nat': [116, 119, None], 'id_art': [None, None, 318]},
120: {'name': ['Jaguari'], 'id_nat': [120], 'id_art': [None]},
121: {'name': ['Paraibuna'], 'id_nat': [121], 'id_art': [None]},
122: {'name': ['Santa Branca'], 'id_nat': [122], 'id_art': [None]},
123: {'name': ['Funil'], 'id_nat': [123], 'id_art': [None]},
124: {'name': ['Lajes'], 'id_nat': [202], 'id_art': [132]},
#125: {'name': ['Santa Cecília', 'Santa Cecília Bombeamento'], 'id_nat': [125, None], 'id_art': [None, 298]},
125: {'name': ['Santa Cecília'], 'id_nat': [125], 'id_art': [None]},
126: {'name': ['Picada'], 'id_nat': [197], 'id_art': [None]},
127: {'name': ['Sobragi'], 'id_nat': [198], 'id_art': [None]},
129: {'name': ['Simplício', 'Anta'], 'id_nat': [None, 129], 'id_art': [126, 127]},
#130: {'name': ['Ilha dos Pombos'], 'id_nat': [130], 'id_art': [299]},
130: {'name': ['Ilha dos Pombos'], 'id_nat': [130], 'id_art': [None]},
131: {'name': ['Nilo Peçanha'], 'id_nat': [None], 'id_art': [131]},
132: {'name': ['Fontes'], 'id_nat': [202], 'id_art': [303]},
133: {'name': ['Pereira Passos'], 'id_nat': [202], 'id_art': [306]},
134: {'name': ['Salto Grande'], 'id_nat': [134], 'id_art': [None]},
135: {'name': ['Porto Estrela'], 'id_nat': [263], 'id_art': [None]},
139: {'name': ['Candonga'], 'id_nat': [149], 'id_art': [None]},
141: {'name': ['Baguari'], 'id_nat': [141], 'id_art': [None]},
143: {'name': ['Aimorés'], 'id_nat': [148], 'id_art': [None]},
144: {'name': ['Mascarenhas'], 'id_nat': [144], 'id_art': [None]},
148: {'name': ['Irapé'], 'id_nat': [255], 'id_art': [None]},
153: {'name': ['São Domingos'], 'id_nat': [154], 'id_art': [None]},
154: {'name': ['Itapebi'], 'id_nat': [188], 'id_art': [None]},
155: {'name': ['Retiro Baixo'], 'id_nat': [155], 'id_art': [None]},
156: {'name': ['Três Marias'], 'id_nat': [156], 'id_art': [None]},
162: {'name': ['Queimado'], 'id_nat': [158], 'id_art': [None]},
169: {'name': ['Sobradinho Incremental', 'Sobradinho'], 'id_nat': [168, 169], 'id_art': [None, None]},
172: {'name': ['Itaparica Incremental', 'Itaparica'], 'id_nat': [171, 172], 'id_art': [None, None]},
173: {'name': ['Moxotó'], 'id_nat': [173], 'id_art': [None]},
174: {'name': ['Paulo Afonso'], 'id_nat': [175], 'id_art': [None]},
176: {'name': ['Complexo Paulo Afonso-Moxotó'], 'id_nat': [176], 'id_art': [None]},
178: {'name': ['Xingó'], 'id_nat': [178], 'id_art': [None]},
180: {'name': ['Tocos', 'Tocos Vertimento'], 'id_nat': [201, None], 'id_art': [None, 317]},
181: {'name': ['Santana', 'Santana Vertimento'], 'id_nat': [203, None], 'id_art': [315, 304]},
182: {'name': ['Vigário'], 'id_nat': [None], 'id_art': [316]},
189: {'name': ['Pedra do Cavalo'], 'id_nat': [254], 'id_art': [None]},
190: {'name': ['Boa Esperança'], 'id_nat': [190], 'id_art': [None]},
192: {'name': ['Guilman-Amorin'], 'id_nat': [262], 'id_art': [None]},
193: {'name': ['Antônio Dias +Sá Carvalho'], 'id_nat': [183], 'id_art': [None]},
195: {'name': ['Jauru'], 'id_nat': [295], 'id_art': [None]},
196: {'name': ['Guaporé'], 'id_nat': [296], 'id_art': [None]},
203: {'name': ['Corumbá III'], 'id_nat': [23], 'id_art': [None]},
204: {'name': ['Cachoeira Caldeirão'], 'id_nat': [204], 'id_art': [None]},
215: {'name': ['Salto Pilão'], 'id_nat': [101], 'id_art': [None]},
217: {'name': ['Rosal'], 'id_nat': [196], 'id_art': [None]},
227: {'name': ['Sinop'], 'id_nat': [227], 'id_art': [None]},
228: {'name': ['Colider'], 'id_nat': [228], 'id_art': [None]},
229: {'name': ['Teles Pires'], 'id_nat': [229], 'id_art': [None]},
230: {'name': ['São Manoel'], 'id_nat': [230], 'id_art': [None]},
241: {'name': ['Salto do Rio Verdinho'], 'id_nat': [241], 'id_art': [None]},
249: {'name': ['Ourinhos'], 'id_nat': [249], 'id_art': [None]},
251: {'name': ['Serra da Mesa'], 'id_nat': [270], 'id_art': [None]},
252: {'name': ['Cana Brava'], 'id_nat': [191], 'id_art': [None]},
253: {'name': ['São Salvador'], 'id_nat': [253], 'id_art': [None]},
257: {'name': ['Peixe Angical'], 'id_nat': [257], 'id_art': [None]},
261: {'name': ['Lajeado'], 'id_nat': [273], 'id_art': [None]},
262: {'name': ['Salto'], 'id_nat': [294], 'id_art': [None]},
267: {'name': ['Estreito Tocantins'], 'id_nat': [271], 'id_art': [None]},
272: {'name': ['Curuá-Una'], 'id_nat': [277], 'id_art': [None]},
275: {'name': ['Tucuruí'], 'id_nat': [275], 'id_art': [None]},
276: {'name': ['Rondon 2'], 'id_nat': [145], 'id_art': [None]},
277: {'name': ['Balbina'], 'id_nat': [269], 'id_art': [None]},
278: {'name': ['Manso'], 'id_nat': [278], 'id_art': [None]},
279: {'name': ['Samuel'], 'id_nat': [279], 'id_art': [None]},
280: {'name': ['Coaracy Nunes'], 'id_nat': [280], 'id_art': [None]},
281: {'name': ['Ponte de Pedra'], 'id_nat': [281], 'id_art': [None]},
283: {'name': ['Santa Clara MG'], 'id_nat': [283], 'id_art': [None]},
284: {'name': ['Ferreira Gomes'], 'id_nat': [297], 'id_art': [None]},
285: {'name': ['Jirau'], 'id_nat': [285], 'id_art': [None]},
286: {'name': ['Santo Antônio do Jari'], 'id_nat': [290], 'id_art': [None]},
287: {'name': ['Santo Antônio'], 'id_nat': [287], 'id_art': [None]},
288: {'name': ['Posto', 'Belo Monte Artificial'], 'id_nat': [300, None], 'id_art': [None, 292]},
290: {'name': ['Espora'], 'id_nat': [99], 'id_art': [None]},
304: {'name': ['Itiquira I e II'], 'id_nat': [259], 'id_art': [None]},
305: {'name': ['Itiquira II'], 'id_nat': [252], 'id_art': [None]},
310: {'name': ['Dardanelos'], 'id_nat': [291], 'id_art': [None]},
311: {'name': ['Caçu'], 'id_nat': [247], 'id_art': [None]},
312: {'name': ['Barra dos Coqueiros'], 'id_nat': [248], 'id_art': [None]},
314: {'name': ['Pimental Artificial'], 'id_nat': [None], 'id_art': [302]},
315: {'name': ['Foz do Rio Claro'], 'id_nat': [261], 'id_art': [None]},
319: {'name': ['Mauá'], 'id_nat': [57], 'id_art': [None]},
921: {'name': ['Tocos_Lajes'], 'id_nat': [None], 'id_art': [921]},
# 922: {'name': ['Barra do Brauna'], 'id_nat': [135], 'id_art': [None]},
}

calculated_stations = {
    1: {
        'name': 'Camargos',
        'basin': 'Grande',
        'river': 'Grande',
        'status': 'Operação',
        'type': 'Natural',
        'formula': None,
        'dep_stations': None,
        've_included': True,
        'observations': None
    },
    2: {
        'name': 'Itutinga',
        'basin': 'Grande',
        'river': 'Grande',
        'status': 'Operação',
        'type': 'Natural',
        'formula': None,
        'dep_stations': None,
        've_included': True,
        'observations': None
    },
    6: {
        'name': 'Furnas',
        'basin': 'Grande',
        'river': 'Grande',
        'status': 'Operação',
        'type': 'Natural',
        'formula': None,
        'dep_stations': None,
        've_included': True,
        'observations': None
    },
    7: {
        'name': 'Mascarenhas de Moraes',
        'basin': 'Grande',
        'river': 'Grande',
        'status': 'Operação',
        'type': 'Natural',
        'formula': None,
        'dep_stations': None,
        've_included': True,
        'observations': None
    },
    8: {
        'name': 'Estreito',
        'basin': 'Grande',
        'river': 'Grande',
        'status': 'Operação',
        'type': 'Natural',
        'formula': None,
        'dep_stations': None,
        've_included': True,
        'observations': None
    },
    9: {
        'name': 'Jaguara',
        'basin': 'Grande',
        'river': 'Grande',
        'status': 'Operação',
        'type': 'Natural',
        'formula': None,
        'dep_stations': None,
        've_included': True,
        'observations': None
    },
    10: {
        'name': 'Igarapava',
        'basin': 'Grande',
        'river': 'Grande',
        'status': 'Operação',
        'type': 'Natural',
        'formula': None,
        'dep_stations': None,
        've_included': True,
        'observations': None
    },
    11: {
        'name': 'Volta Grande',
        'basin': 'Grande',
        'river': 'Grande',
        'status': 'Operação',
        'type': 'Natural',
        'formula': None,
        'dep_stations': None,
        've_included': True,
        'observations': None
    },
    12: {
        'name': 'Porto Colômbia',
        'basin': 'Grande',
        'river': 'Grande',
        'status': 'Operação',
        'type': 'Natural',
        'formula': None,
        'dep_stations': None,
        've_included': True,
        'observations': None
    },
    14: {
        'name': 'Caconde',
        'basin': 'Grande',
        'river': 'Pardo',
        'status': 'Operação',
        'type': 'Natural',
        'formula': None,
        'dep_stations': None,
        've_included': True,
        'observations': None
    },
    15: {
        'name': 'Euclides da Cunha',
        'basin': 'Grande',
        'river': 'Pardo',
        'status': 'Operação',
        'type': 'Natural',
        'formula': None,
        'dep_stations': None,
        've_included': True,
        'observations': None
    },
    16: {
        'name': 'Limoeiro',
        'basin': 'Grande',
        'river': 'Pardo',
        'status': 'Operação',
        'type': 'Natural',
        'formula': None,
        'dep_stations': None,
        've_included': True,
        'observations': None
    },
    17: {
        'name': 'Marimbondo',
        'basin': 'Grande',
        'river': 'Grande',
        'status': 'Operação',
        'type': 'Natural',
        'formula': None,
        'dep_stations': None,
        've_included': True,
        'observations': None
    },
    18: {
        'name': 'Água Vermelha',
        'basin': 'Grande',
        'river': 'Grande',
        'status': 'Operação',
        'type': 'Natural',
        'formula': None,
        'dep_stations': None,
        've_included': True,
        'observations': None
    },
    22: {
        'name': 'Batalha',
        'basin': 'Paranaíba',
        'river': 'São Marcos',
        'status': 'Operação',
        'type': 'Natural',
        'formula': None,
        'dep_stations': None,
        've_included': True,
        'observations': None
    },
    23: {
        'name': 'Corumbá III',
        'basin': 'Paranaíba',
        'river': 'Corumbá',
        'status': 'Operação',
        'type': 'Natural',
        'formula': None,
        'dep_stations': None,
        've_included': True,
        'observations': None
    },
    24: {
        'name': 'Emborcação',
        'basin': 'Paranaíba',
        'river': 'Paranaíba',
        'status': 'Operação',
        'type': 'Natural',
        'formula': None,
        'dep_stations': None,
        've_included': True,
        'observations': None
    },
    25: {
        'name': 'Nova Ponte',
        'basin': 'Paranaíba',
        'river': 'Araguari',
        'status': 'Operação',
        'type': 'Natural',
        'formula': None,
        'dep_stations': None,
        've_included': True,
        'observations': None
    },
    28: {
        'name': 'Capim Branco 2',
        'basin': 'Paranaíba',
        'river': 'Araguari',
        'status': 'Operação',
        'type': 'Natural',
        'formula': None,
        'dep_stations': None,
        've_included': True,
        'observations': None
    },
    31: {
        'name': 'Itumbiara',
        'basin': 'Paranaíba',
        'river': 'Paranaíba',
        'status': 'Operação',
        'type': 'Natural',
        'formula': None,
        'dep_stations': None,
        've_included': True,
        'observations': None
    },
    32: {
        'name': 'Cachoeira Dourada',
        'basin': 'Paranaíba',
        'river': 'Paranaíba',
        'status': 'Operação',
        'type': 'Natural',
        'formula': None,
        'dep_stations': None,
        've_included': True,
        'observations': None
    },
    33: {
        'name': 'São Simão',
        'basin': 'Paranaíba',
        'river': 'Paranaíba',
        'status': 'Operação',
        'type': 'Natural',
        'formula': None,
        'dep_stations': None,
        've_included': True,
        'observations': None
    },
    34: {
        'name': 'Ilha Solteira',
        'basin': 'Paraná',
        'river': 'Paraná',
        'status': 'Operação',
        'type': 'Natural',
        'formula': None,
        'dep_stations': None,
        've_included': True,
        'observations': None
    },
    37: {
        'name': 'Barra Bonita',
        'basin': 'Tietê',
        'river': 'Tietê',
        'status': 'Operação',
        'type': 'Artificial',
        'formula': lambda x: x[0] - 0.1 * (x[1] - x[2] - x[3]) - x[2] - x[3],
        'dep_stations': [237, 161, 117, 118],
        've_included': False,
        'observations': 'Considera bombeamento para Henry Borden'
    },
    38: {
        'name': 'Bariri',
        'basin': 'Tietê',
        'river': 'Tietê',
        'status': 'Operação',
        'type': 'Artificial',
        'formula': lambda x: x[0] - 0.1 * (x[1] - x[2] - x[3]) - x[2] - x[3],
        'dep_stations': [238, 161, 117, 118],
        've_included': False,
        'observations': 'Considera bombeamento para Henry Borden'
    },
    39: {
        'name': 'Ibitinga',
        'basin': 'Tietê',
        'river': 'Tietê',
        'status': 'Operação',
        'type': 'Artificial',
        'formula': lambda x: x[0] - 0.1 * (x[1] - x[2] - x[3]) - x[2] - x[3],
        'dep_stations': [239, 161, 117, 118],
        've_included': False,
        'observations': 'Considera bombeamento para Henry Borden'
    },
    40: {
        'name': 'Promissão',
        'basin': 'Tietê',
        'river': 'Tietê',
        'status': 'Operação',
        'type': 'Artificial',
        'formula': lambda x: x[0] - 0.1 * (x[1] - x[2] - x[3]) - x[2] - x[3],
        'dep_stations': [240, 161, 117, 118],
        've_included': False,
        'observations': 'Considera bombeamento para Henry Borden'
    },
    42: {
        'name': 'Nova Avanhandava',
        'basin': 'Tietê',
        'river': 'Tietê',
        'status': 'Operação',
        'type': 'Artificial',
        'formula': lambda x: x[0] - 0.1 * (x[1] - x[2] - x[3]) - x[2] - x[3],
        'dep_stations': [242, 161, 117, 118],
        've_included': False,
        'observations': 'Considera bombeamento para Henry Borden'
    },
    43: {
        'name': 'Três Irmãos',
        'basin': 'Tietê',
        'river': 'Tietê',
        'status': 'Operação',
        'type': 'Artificial',
        'formula': lambda x: x[0] - 0.1 * (x[1] - x[2] - x[3]) - x[2] - x[3],
        'dep_stations': [243, 161, 117, 118],
        've_included': False,
        'observations': 'Considera bombeamento para Henry Borden'
    },
    44: {
        'name': 'Ilha Solteira Equivalente',
        'basin': 'Paraná',
        'river': 'Tietê e Paraná',
        'status': 'Operação',
        'type': 'Artificial',
        'formula': lambda x: x[0] - 0.1 * (x[1] - x[2] - x[3]) - x[2] - x[3],
        'dep_stations': [244, 161, 117, 118],
        've_included': False,
        'observations': 'Considera bombeamento para Henry Borden'
    },
    45: {
        'name': 'Jupiá',
        'basin': 'Paraná',
        'river': 'Paraná',
        'status': 'Operação',
        'type': 'Artificial',
        'formula': lambda x: x[0] - 0.1 * (x[1] - x[2] - x[3]) - x[2] - x[3],
        'dep_stations': [245, 161, 117, 118],
        've_included': False,
        'observations': 'Considera bombeamento para Henry Borden'
    },
    46: {
        'name': 'Porto Primavera',
        'basin': 'Paraná',
        'river': 'Paraná',
        'status': 'Operação',
        'type': 'Artificial',
        'formula': lambda x: x[0] - 0.1 * (x[1] - x[2] - x[3]) - x[2] - x[3],
        'dep_stations': [246, 161, 117, 118],
        've_included': False,
        'observations': 'Considera bombeamento para Henry Borden'
    },
    47: {
        'name': 'Jurumirim',
        'basin': 'Paranapanema',
        'river': 'Paranapanema',
        'status': 'Operação',
        'type': 'Natural',
        'formula': None,
        'dep_stations': None,
        've_included': True,
        'observations': None
    },
    48: {
        'name': 'Piraju',
        'basin': 'Paranapanema',
        'river': 'Paranapanema',
        'status': 'Operação',
        'type': 'Natural',
        'formula': None,
        'dep_stations': None,
        've_included': True,
        'observations': None
    },
    49: {
        'name': 'Chavantes',
        'basin': 'Paranapanema',
        'river': 'Paranapanema',
        'status': 'Operação',
        'type': 'Natural',
        'formula': None,
        'dep_stations': None,
        've_included': True,
        'observations': None
    },
    50: {
        'name': 'Lucas Garcez',
        'basin': 'Paranapanema',
        'river': 'Paranapanema',
        'status': 'Operação',
        'type': 'Natural',
        'formula': None,
        'dep_stations': None,
        've_included': True,
        'observations': None
    },
    51: {
        'name': 'Canoas 2',
        'basin': 'Paranapanema',
        'river': 'Paranapanema',
        'status': 'Operação',
        'type': 'Natural',
        'formula': None,
        'dep_stations': None,
        've_included': True,
        'observations': None
    },
    52: {
        'name': 'Canoas 1',
        'basin': 'Paranapanema',
        'river': 'Paranapanema',
        'status': 'Operação',
        'type': 'Natural',
        'formula': None,
        'dep_stations': None,
        've_included': True,
        'observations': None
    },
    # 54: {
    #     'name': 'Santa Branca Tibagi',
    #     'basin': 'Paranapanema',
    #     'river': 'Tibagi',
    #     'status': 'Expansão',
    #     'type': 'Natural',
    #     'formula': None,
    #     'dep_stations': None,
    #     've_included': False,
    #     'observations': None
    # },
    57: {
        'name': 'Mauá',
        'basin': 'Paranapanema',
        'river': 'Tibagi',
        'status': 'Operação',
        'type': 'Natural',
        'formula': None,
        'dep_stations': None,
        've_included': True,
        'observations': None
    },
    61: {
        'name': 'Capivara',
        'basin': 'Paranapanema',
        'river': 'Paranapanema',
        'status': 'Operação',
        'type': 'Natural',
        'formula': None,
        'dep_stations': None,
        've_included': True,
        'observations': None
    },
    62: {
        'name': 'Taquarucu',
        'basin': 'Paranapanema',
        'river': 'Paranapanema',
        'status': 'Operação',
        'type': 'Natural',
        'formula': None,
        'dep_stations': None,
        've_included': True,
        'observations': None
    },
    63: {
        'name': 'Rosana',
        'basin': 'Paranapanema',
        'river': 'Paranapanema',
        'status': 'Operação',
        'type': 'Natural',
        'formula': None,
        'dep_stations': None,
        've_included': True,
        'observations': None
    },
    66: {
        'name': 'Itaipu',
        'basin': 'Paraná',
        'river': 'Paraná',
        'status': 'Operação',
        'type': 'Artificial',
        'formula': lambda x: x[0] - 0.1 * (x[1] - x[2] - x[3]) - x[2] - x[3],
        'dep_stations': [266, 161, 117, 118],
        've_included': False,
        'observations': None
    },
    70: {
        'name': 'Jordão',
        'basin': 'Iguaçu',
        'river': 'Jordão e Iguaçu',
        'status': 'Operação',
        'type': 'Artificial',
        'formula': lambda x: x[0] - x[0].apply(lambda y: min(173.5, y - 10)),
        'dep_stations': [73],
        've_included': False,
        'observations': 'Reduzida da vazão desviada para o rio Iguaçu a montante de Segredo'
    },
    71: {
        'name': 'Santa Clara PR',
        'basin': 'Iguaçu',
        'river': 'Jordão',
        'status': 'Operação',
        'type': 'Natural',
        'formula': None,
        'dep_stations': None,
        've_included': True,
        'observations': None
    },
    72: {
        'name': 'Fundão',
        'basin': 'Iguaçu',
        'river': 'Jordão e Iratim',
        'status': 'Operação',
        'type': 'Natural',
        'formula': None,
        'dep_stations': None,
        've_included': True,
        'observations': None
    },
    73: {
        'name': 'Jordão',
        'basin': 'Iguaçu',
        'river': 'Jordão e Iguaçu',
        'status': 'Operação',
        'type': 'Natural',
        'formula': None,
        'dep_stations': None,
        've_included': True,
        'observations': None
    },
    74: {
        'name': 'Foz do Areia',
        'basin': 'Iguaçu',
        'river': 'Iguaçu',
        'status': 'Operação',
        'type': 'Natural',
        'formula': None,
        'dep_stations': None,
        've_included': True,
        'observations': None
    },
    75: {
        'name': 'Segredo + Desvio',
        'basin': 'Iguaçu',
        'river': 'Iguaçu',
        'status': 'Operação',
        'type': 'Artificial',
        'formula': lambda x: x[0] + x[1].apply(lambda y: min(173.5, y - 10)),
        'dep_stations': [76, 73],
        've_included': False,
        'observations': 'Acréscimo de Desvio Jordão a montante'
    },
    76: {
        'name': 'Segredo',
        'basin': 'Iguaçu',
        'river': 'Iguaçu',
        'status': 'Operação',
        'type': 'Natural',
        'formula': None,
        'dep_stations': None,
        've_included': True,
        'observations': None
    },
    77: {
        'name': 'Salto Santiago',
        'basin': 'Iguaçu',
        'river': 'Iguaçu',
        'status': 'Operação',
        'type': 'Natural',
        'formula': None,
        'dep_stations': None,
        've_included': True,
        'observations': None
    },
    78: {
        'name': 'Salto Osório',
        'basin': 'Iguaçu',
        'river': 'Iguaçu',
        'status': 'Operação',
        'type': 'Natural',
        'formula': None,
        'dep_stations': None,
        've_included': True,
        'observations': None
    },
    81: {
        'name': 'Baixo Iguaçu',
        'basin': 'Iguaçu',
        'river': 'Iguaçu',
        'status': 'Expansão',
        'type': 'Natural',
        'formula': None,
        'dep_stations': None,
        've_included': True,
        'observations': None
    },
    88: {
        'name': 'São Roque',
        'basin': 'Uruguai',
        'river': 'Canoas',
        'status': 'Expansão',
        'type': 'Natural',
        'formula': None,
        'dep_stations': None,
        've_included': True,
        'observations': None
    },
    89: {
        'name': 'Garibaldi',
        'basin': 'Uruguai',
        'river': 'Canoas',
        'status': 'Operação',
        'type': 'Natural',
        'formula': None,
        'dep_stations': None,
        've_included': True,
        'observations': None
    },
    92: {
        'name': 'Itá',
        'basin': 'Uruguai',
        'river': 'Uruguai',
        'status': 'Operação',
        'type': 'Natural',
        'formula': None,
        'dep_stations': None,
        've_included': True,
        'observations': None
    },
    93: {
        'name': 'Passo Fundo',
        'basin': 'Uruguai',
        'river': 'Passo Fundo',
        'status': 'Operação',
        'type': 'Natural',
        'formula': None,
        'dep_stations': None,
        've_included': True,
        'observations': None
    },
    94: {
        'name': 'Foz Chapecó',
        'basin': 'Uruguai',
        'river': 'Uruguai',
        'status': 'Operação',
        'type': 'Natural',
        'formula': None,
        'dep_stations': None,
        've_included': True,
        'observations': None
    },
    97: {
        'name': 'Monte Claro',
        'basin': 'Jacuí',
        'river': 'Taquari-Antas',
        'status': 'Operação',
        'type': 'Natural',
        'formula': None,
        'dep_stations': None,
        've_included': True,
        'observations': None
    },
    98: {
        'name': 'Castro Alves',
        'basin': 'Jacuí',
        'river': 'Taquari-Antas',
        'status': 'Operação',
        'type': 'Natural',
        'formula': None,
        'dep_stations': None,
        've_included': True,
        'observations': None
    },
    99: {
        'name': 'Espora',
        'basin': 'Paranaíba',
        'river': 'Corrente',
        'status': 'Operação',
        'type': 'Natural',
        'formula': None,
        'dep_stations': None,
        've_included': True,
        'observations': None
    },
    101: {
        'name': 'Salto Pilão',
        'basin': 'Atlântico Sudeste',
        'river': 'Itajaí-Açu',
        'status': 'Operação',
        'type': 'Natural',
        'formula': None,
        'dep_stations': None,
        've_included': True,
        'observations': None
    },
    102: {
        'name': 'São José',
        'basin': 'Uruguai',
        'river': 'Ijuí',
        'status': 'Operação',
        'type': 'Natural',
        'formula': None,
        'dep_stations': None,
        've_included': True,
        'observations': None
    },
    103: {
        'name': 'Passo São João',
        'basin': 'Uruguai',
        'river': 'Ijuí',
        'status': 'Operação',
        'type': 'Natural',
        'formula': None,
        'dep_stations': None,
        've_included': True,
        'observations': None
    },
    104: {
        'name': 'Traição',
        'basin': 'Tietê',
        'river': 'Pinheiros',
        'status': 'Operação',
        'type': 'Natural',
        'formula': lambda x: x[0] + x[1],
        'dep_stations': [117, 118],
        've_included': True,
        'observations': None
    },
    109: {
        'name': 'Pedreira',
        'basin': 'Tietê',
        'river': 'Pinheiros',
        'status': 'Operação',
        'type': 'Natural',
        'formula': lambda x: x[0],
        'dep_stations': [118],
        've_included': True,
        'observations': None
    },
    110: {
        'name': 'Ernestina',
        'basin': 'Jacuí',
        'river': 'Jacuí',
        'status': 'Operação',
        'type': 'Natural',
        'formula': None,
        'dep_stations': None,
        've_included': True,
        'observations': None
    },
    111: {
        'name': 'Passo Real',
        'basin': 'Jacuí',
        'river': 'Jacuí',
        'status': 'Operação',
        'type': 'Natural',
        'formula': None,
        'dep_stations': None,
        've_included': True,
        'observations': None
    },
    112: {
        'name': 'Jacuí',
        'basin': 'Jacuí',
        'river': 'Jacuí',
        'status': 'Operação',
        'type': 'Natural',
        'formula': None,
        'dep_stations': None,
        've_included': True,
        'observations': None
    },
    113: {
        'name': 'Itaúba',
        'basin': 'Jacuí',
        'river': 'Jacuí',
        'status': 'Operação',
        'type': 'Natural',
        'formula': None,
        'dep_stations': None,
        've_included': True,
        'observations': None
    },
    114: {
        'name': 'Dona Francisca',
        'basin': 'Jacuí',
        'river': 'Jacuí',
        'status': 'Operação',
        'type': 'Natural',
        'formula': None,
        'dep_stations': None,
        've_included': True,
        'observations': None
    },
    115: {
        'name': 'Capivari Cachoeira',
        'basin': 'Capivari-Cachoeira',
        'river': 'Capivari e Cachoeira',
        'status': 'Operação',
        'type': 'Natural',
        'formula': None,
        'dep_stations': None,
        've_included': True,
        'observations': None
    },
    116: {
        'name': 'Pedras',
        'basin': 'Cubatão',
        'river': 'Rio das Pedras',
        'status': 'Operação',
        'type': 'Natural',
        'formula': lambda x: x[0] - x[1],
        'dep_stations': [119, 118],
        've_included': True,
        'observations': None
    },
    117: {
        'name': 'Guarapiranga',
        'basin': 'Tietê',
        'river': 'Guarapiranga',
        'status': 'Operação',
        'type': 'Natural',
        'formula': None,
        'dep_stations': None,
        've_included': True,
        'observations': None
    },
    118: {
        'name': 'Billings',
        'basin': 'Tietê',
        'river': 'Pinheiros',
        'status': 'Operação',
        'type': 'Natural',
        'formula': None,
        'dep_stations': None,
        've_included': True,
        'observations': None
    },
    119: {
        'name': 'Billings + Pedras',
        'basin': 'Tietê-Cubatão',
        'river': 'Pinheiros e Pedras',
        'status': 'Operação',
        'type': 'Natural',
        'formula': lambda x: (x[0] - 0.185) / 0.8103,
        'dep_stations': [118],
        've_included': True,
        'observations': 'Vazão Natural formada pelo reservatório Billings considerando a contribuição do reservatório '
                        'de Pedras'
    },
    120: {
        'name': 'Jaguari',
        'basin': 'Paraíba do Sul',
        'river': 'Jaguari',
        'status': 'Operação',
        'type': 'Natural',
        'formula': None,
        'dep_stations': None,
        've_included': True,
        'observations': None
    },
    121: {
        'name': 'Paraibuna',
        'basin': 'Paraíba do Sul',
        'river': 'Paraibuna e Paraitinga',
        'status': 'Operação',
        'type': 'Natural',
        'formula': None,
        'dep_stations': None,
        've_included': True,
        'observations': None
    },
    122: {
        'name': 'Santa Branca',
        'basin': 'Paraíba do Sul',
        'river': 'Paraíba do Sul',
        'status': 'Operação',
        'type': 'Natural',
        'formula': None,
        'dep_stations': None,
        've_included': True,
        'observations': None
    },
    123: {
        'name': 'Funil',
        'basin': 'Paraíba do Sul',
        'river': 'Paraíba do Sul',
        'status': 'Operação',
        'type': 'Natural',
        'formula': None,
        'dep_stations': None,
        've_included': True,
        'observations': None
    },
    125: {
        'name': 'Santa Cecília',
        'basin': 'Paraíba do Sul',
        'river': 'Paraíba do Sul',
        'status': 'Operação',
        'type': 'Natural',
        'formula': None,
        'dep_stations': None,
        've_included': True,
        'observations': None
    },
    126: {
        'name': 'Simplício',
        'basin': 'Paraíba do Sul',
        'river': 'Paraíba do Sul',
        'status': 'Operação',
        'type': 'Artificial',
        'formula': lambda x: x[0].apply(lambda y: (max(0, y - 90), 340)[y >= 430]),
        'dep_stations': [127],
        've_included': False,
        'observations': 'Limitação de vazão máxima pelo túnel de desvio para Simplicio, obedecendo também as regras de '
                        'vazão mínima na bacia'
    },
    127: {
        'name': 'Anta',
        'basin': 'Paraíba do Sul',
        'river': 'Paraíba do Sul',
        'status': 'Operação',
        'type': 'Artificial',
        'formula': lambda x: x[0] - x[1] - x[2] + x[3],
        'dep_stations': [129, 298, 203, 304],
        've_included': False,
        'observations': 'Desconto do bombeamento em Santa Cecília e acréscimo de vertimento de Santana'
    },
    129: {
        'name': 'Anta',
        'basin': 'Paraíba do Sul',
        'river': 'Paraíba do Sul',
        'status': 'Operação',
        'type': 'Natural',
        'formula': None,
        'dep_stations': None,
        've_included': True,
        'observations': None
    },
    130: {
        'name': 'Ilha Pombos',
        'basin': 'Paraíba do Sul',
        'river': 'Paraíba do Sul',
        'status': 'Operação',
        'type': 'Natural',
        'formula': None,
        'dep_stations': None,
        've_included': True,
        'observations': None
    },
    131: {
        'name': 'Nilo Peçanha',
        'basin': 'Paraíba do Sul',
        'river': None,
        'status': 'Operação',
        'type': 'Artificial',
        'formula': lambda x: x[0].apply(lambda y: min(y, 144)),
        'dep_stations': [316],
        've_included': False,
        'observations': 'Limitado à máxima vazão defluente do reservatório de Vigário'
    },
    132: {
        'name': 'Lajes',
        'basin': 'Paraíba do Sul',
        'river': 'Ribeirão das Lajes',
        'status': 'Operação',
        'type': 'Artificial',
        'formula': lambda x: x[0] + x[1].apply(lambda y: min(y, 25)),
        'dep_stations': [202, 201],
        've_included': False,
        'observations': 'Com acréscimo do Desvio em Tocos limitado em, no máximo, 25 m³/s'
    },
    134: {
        'name': 'Salto Grande',
        'basin': 'Doce',
        'river': 'Doce',
        'status': 'Operação',
        'type': 'Natural',
        'formula': None,
        'dep_stations': None,
        've_included': True,
        'observations': None
    },
    141: {
        'name': 'Baguari',
        'basin': 'Doce',
        'river': 'Doce',
        'status': 'Operação',
        'type': 'Natural',
        'formula': None,
        'dep_stations': None,
        've_included': True,
        'observations': None
    },
    144: {
        'name': 'Mascarenhas',
        'basin': 'Doce',
        'river': 'Doce',
        'status': 'Operação',
        'type': 'Natural',
        'formula': None,
        'dep_stations': None,
        've_included': True,
        'observations': None
    },
    145: {
        'name': 'Rondon II',
        'basin': 'Amazonas',
        'river': 'Comemoração',
        'status': 'Operação',
        'type': 'Natural',
        'formula': None,
        'dep_stations': None,
        've_included': True,
        'observations': None
    },
    148: {
        'name': 'Aimorés',
        'basin': 'Doce',
        'river': 'Doce',
        'status': 'Operação',
        'type': 'Natural',
        'formula': None,
        'dep_stations': None,
        've_included': True,
        'observations': None
    },
    149: {
        'name': 'Candonga',
        'basin': 'Doce',
        'river': 'Doce',
        'status': 'Operação',
        'type': 'Natural',
        'formula': None,
        'dep_stations': None,
        've_included': True,
        'observations': None
    },
    154: {
        'name': 'São Domingos',
        'basin': 'Paraná',
        'river': 'Verde',
        'status': 'Operação',
        'type': 'Natural',
        'formula': None,
        'dep_stations': None,
        've_included': True,
        'observations': 'Adicionado posteriormente (não se encontra no pdf)'
    },
    155: {
        'name': 'Retiro Baixo',
        'basin': 'São Francisco',
        'river': 'Paraopeba',
        'status': 'Operação',
        'type': 'Natural',
        'formula': None,
        'dep_stations': None,
        've_included': True,
        'observations': None
    },
    156: {
        'name': 'Três Marias',
        'basin': 'São Francisco',
        'river': 'São Francisco',
        'status': 'Operação',
        'type': 'Natural',
        'formula': None,
        'dep_stations': None,
        've_included': True,
        'observations': None
    },
    158: {
        'name': 'Queimado',
        'basin': 'São Francisco',
        'river': 'Preto',
        'status': 'Operação',
        'type': 'Natural',
        'formula': None,
        'dep_stations': None,
        've_included': True,
        'observations': None
    },
    160: {
        'name': 'Ponte Nova',
        'basin': 'Tietê',
        'river': 'Tietê',
        'status': 'Operação',
        'type': 'Natural',
        'formula': None,
        'dep_stations': None,
        've_included': True,
        'observations': None
    },
    161: {
        'name': 'Edgard de Souza com Tributários',
        'basin': 'Tietê',
        'river': 'Tietê',
        'status': 'Operação',
        'type': 'Natural',
        'formula': None,
        'dep_stations': None,
        've_included': True,
        'observations': None
    },
    164: {
        'name': 'Edgard de Souza sem Tributários',
        'basin': 'Tietê',
        'river': 'Tietê',
        'status': 'Operação',
        'type': 'Natural',
        'formula': lambda x: x[0] - x[1] - x[2],
        'dep_stations': [161, 117, 118],
        've_included': False,
        'observations': 'Vazões de Edgard de Souza sem a contribuição do canal Pinheiros'
    },
    168: {
        'name': 'Sobradinho Incremental',
        'basin': 'São Francisco',
        'river': 'São Francisco',
        'status': 'Operação',
        'type': 'Natural',
        'formula': None,
        'dep_stations': None,
        've_included': True,
        'observations': 'Vazões incrementais entre Três Marias e Sobradinho'
    },
    169: {
        'name': 'Sobradinho',
        'basin': 'São Francisco',
        'river': 'São Francisco',
        'status': 'Operação',
        'type': 'Natural',
        'formula': None,
        'dep_stations': None,
        've_included': True,
        'observations': None
    },
    171: {
        'name': 'Itaparica Incremental',
        'basin': 'São Francisco',
        'river': 'São Francisco',
        'status': 'Operação',
        'type': 'Natural',
        'formula': None,
        'dep_stations': None,
        've_included': True,
        'observations': 'Vazões incrementais entre Sobradinho e Itaparica'
    },
    172: {
        'name': 'Itaparica',
        'basin': 'São Francisco',
        'river': 'São Francisco',
        'status': 'Operação',
        'type': 'Natural',
        'formula': None,
        'dep_stations': None,
        've_included': True,
        'observations': None
    },
    173: {
        'name': 'Moxotó',
        'basin': 'São Francisco',
        'river': 'São Francisco',
        'status': 'Operação',
        'type': 'Natural',
        'formula': lambda x: x[0],
        'dep_stations': [172],
        've_included': True,
        'observations': None
    },
    175: {
        'name': 'Paulo Afonso',
        'basin': 'São Francisco',
        'river': 'São Francisco',
        'status': 'Operação',
        'type': 'Natural',
        'formula': None,
        'dep_stations': None,
        've_included': True,
        'observations': None
    },
    176: {
        'name': 'Complexo Paulo Afonso-Moxotó',
        'basin': 'São Francisco',
        'river': 'São Francisco',
        'status': 'Operação',
        'type': 'Natural',
        'formula': lambda x: x[0],
        'dep_stations': [173],
        've_included': True,
        'observations': None
    },
    178: {
        'name': 'Xingó',
        'basin': 'São Francisco',
        'river': 'São Francisco',
        'status': 'Operação',
        'type': 'Natural',
        'formula': None,
        'dep_stations': None,
        've_included': True,
        'observations': None
    },
    183: {
        'name': 'Antônio Dias + Sá Carvalho',
        'basin': 'Doce',
        'river': 'Piracicaba e Severo',
        'status': 'Operação',
        'type': 'Natural',
        'formula': None,
        'dep_stations': None,
        've_included': True,
        'observations': None
    },
    188: {
        'name': 'Itapebi',
        'basin': 'Jequitinhonha',
        'river': 'Jequitinhonha',
        'status': 'Operação',
        'type': 'Natural',
        'formula': None,
        'dep_stations': None,
        've_included': True,
        'observations': None
    },
    190: {
        'name': 'Boa Esperança',
        'basin': 'Parnaíba',
        'river': 'Parnaíba',
        'status': 'Operação',
        'type': 'Natural',
        'formula': None,
        'dep_stations': None,
        've_included': True,
        'observations': None
    },
    191: {
        'name': 'Cana Brava',
        'basin': 'Tocantins',
        'river': 'Tocantins',
        'status': 'Operação',
        'type': 'Natural',
        'formula': None,
        'dep_stations': None,
        've_included': True,
        'observations': None
    },
    196: {
        'name': 'Rosal',
        'basin': 'Itabapoana',
        'river': 'Itabapoana',
        'status': 'Operação',
        'type': 'Natural',
        'formula': None,
        'dep_stations': None,
        've_included': True,
        'observations': None
    },
    197: {
        'name': 'Picada',
        'basin': 'Paraíba do Sul',
        'river': 'Peixe',
        'status': 'Operação',
        'type': 'Natural',
        'formula': None,
        'dep_stations': None,
        've_included': True,
        'observations': None
    },
    198: {
        'name': 'Sobragi',
        'basin': 'Paraíba do Sul',
        'river': 'Paraibuna',
        'status': 'Operação',
        'type': 'Natural',
        'formula': None,
        'dep_stations': None,
        've_included': True,
        'observations': None
    },
    201: {
        'name': 'Tocos',
        'basin': 'Paraíba do Sul',
        'river': 'Piraí',
        'status': 'Operação',
        'type': 'Natural',
        'formula': None,
        'dep_stations': None,
        've_included': True,
        'observations': None
    },
    202: {
        'name': 'Lajes + Pereira Passos + Fontes',
        'basin': 'Paraíba do Sul',
        'river': 'Ribeirão das Lajes',
        'status': 'Operação',
        'type': 'Natural',
        'formula': None,
        'dep_stations': None,
        've_included': True,
        'observations': None
    },
    203: {
        'name': 'Santana',
        'basin': 'Paraíba do Sul',
        'river': 'Piraí',
        'status': 'Operação',
        'type': 'Natural',
        'formula': None,
        'dep_stations': None,
        've_included': True,
        'observations': None
    },
    204: {
        'name': 'Cachoeira Caldeirão',
        'basin': 'Araguari',
        'river': 'Araguari',
        'status': 'Operação',
        'type': 'Natural',
        'formula': None,
        'dep_stations': None,
        've_included': True,
        'observations': None
    },
    205: {
        'name': 'Corumbá 4',
        'basin': 'Paranaíba',
        'river': 'Corumbá',
        'status': 'Operação',
        'type': 'Natural',
        'formula': None,
        'dep_stations': None,
        've_included': True,
        'observations': None
    },
    206: {
        'name': 'Miranda',
        'basin': 'Paranaíba',
        'river': 'Araguari',
        'status': 'Operação',
        'type': 'Natural',
        'formula': None,
        'dep_stations': None,
        've_included': True,
        'observations': None
    },
    207: {
        'name': 'Capim Branco 1',
        'basin': 'Paranaíba',
        'river': 'Araguari',
        'status': 'Operação',
        'type': 'Natural',
        'formula': None,
        'dep_stations': None,
        've_included': True,
        'observations': None
    },
    209: {
        'name': 'Corumbá 1',
        'basin': 'Paranaíba',
        'river': 'Corumbá',
        'status': 'Operação',
        'type': 'Natural',
        'formula': None,
        'dep_stations': None,
        've_included': True,
        'observations': None
    },
    211: {
        'name': 'Funil-Grande',
        'basin': 'Grande',
        'river': 'Grande',
        'status': 'Operação',
        'type': 'Natural',
        'formula': None,
        'dep_stations': None,
        've_included': True,
        'observations': None
    },
    215: {
        'name': 'Barra Grande',
        'basin': 'Uruguai',
        'river': 'Pelotas',
        'status': 'Operação',
        'type': 'Natural',
        'formula': None,
        'dep_stations': None,
        've_included': True,
        'observations': None
    },
    216: {
        'name': 'Campos Novos',
        'basin': 'Uruguai',
        'river': 'Canoas',
        'status': 'Operação',
        'type': 'Natural',
        'formula': None,
        'dep_stations': None,
        've_included': True,
        'observations': None
    },
    217: {
        'name': 'Machadinho',
        'basin': 'Uruguai',
        'river': 'Pelotas',
        'status': 'Operação',
        'type': 'Natural',
        'formula': None,
        'dep_stations': None,
        've_included': True,
        'observations': None
    },
    220: {
        'name': 'Monjolinho',
        'basin': 'Uruguai',
        'river': 'Passo Fundo',
        'status': 'Operação',
        'type': 'Natural',
        'formula': None,
        'dep_stations': None,
        've_included': True,
        'observations': None
    },
    222: {
        'name': 'Salto Caxias',
        'basin': 'Iguaçu',
        'river': 'Iguaçu',
        'status': 'Operação',
        'type': 'Natural',
        'formula': None,
        'dep_stations': None,
        've_included': True,
        'observations': None
    },
    227: {
        'name': 'Sinop',
        'basin': 'Amazonas',
        'river': 'Teles Pires',
        'status': 'Operação',
        'type': 'Natural',
        'formula': None,
        'dep_stations': None,
        've_included': True,
        'observations': None
    },
    228: {
        'name': 'Colíder',
        'basin': 'Amazonas',
        'river': 'Teles Pires',
        'status': 'Operação',
        'type': 'Natural',
        'formula': None,
        'dep_stations': None,
        've_included': True,
        'observations': None
    },
    229: {
        'name': 'Teles Pires',
        'basin': 'Amazonas',
        'river': 'Teles Pires',
        'status': 'Operação',
        'type': 'Natural',
        'formula': None,
        'dep_stations': None,
        've_included': True,
        'observations': None
    },
    230: {
        'name': 'São Manoel',
        'basin': 'Amazonas',
        'river': 'Teles Pires',
        'status': 'Operação',
        'type': 'Natural',
        'formula': None,
        'dep_stations': None,
        've_included': True,
        'observations': None
    },
    237: {
        'name': 'Barra Bonita',
        'basin': 'Tietê',
        'river': 'Tietê',
        'status': 'Operação',
        'type': 'Natural',
        'formula': None,
        'dep_stations': None,
        've_included': True,
        'observations': None
    },
    238: {
        'name': 'Bariri',
        'basin': 'Tietê',
        'river': 'Tietê',
        'status': 'Operação',
        'type': 'Natural',
        'formula': None,
        'dep_stations': None,
        've_included': True,
        'observations': None
    },
    239: {
        'name': 'Ibitinga',
        'basin': 'Tietê',
        'river': 'Tietê',
        'status': 'Operação',
        'type': 'Natural',
        'formula': None,
        'dep_stations': None,
        've_included': True,
        'observations': None
    },
    240: {
        'name': 'Promissão',
        'basin': 'Tietê',
        'river': 'Tietê',
        'status': 'Operação',
        'type': 'Natural',
        'formula': None,
        'dep_stations': None,
        've_included': True,
        'observations': None
    },
    241: {
        'name': 'Salto Verdinho',
        'basin': 'Paranaíba',
        'river': 'Verde',
        'status': 'Operação',
        'type': 'Natural',
        'formula': None,
        'dep_stations': None,
        've_included': True,
        'observations': None
    },
    242: {
        'name': 'Nova Avanhandava',
        'basin': 'Tietê',
        'river': 'Tietê',
        'status': 'Operação',
        'type': 'Natural',
        'formula': None,
        'dep_stations': None,
        've_included': True,
        'observations': None
    },
    243: {
        'name': 'Três Irmãos',
        'basin': 'Tietê',
        'river': 'Tietê',
        'status': 'Operação',
        'type': 'Natural',
        'formula': None,
        'dep_stations': None,
        've_included': True,
        'observations': None
    },
    244: {
        'name': 'Ilha Solteira Equivalente',
        'basin': 'Paraná',
        'river': 'Tietê e Paraná',
        'status': 'Operação',
        'type': 'Natural',
        'formula': lambda x: x[0] + x[1],
        'dep_stations': [34, 243],
        've_included': True,
        'observations': None
    },
    245: {
        'name': 'Jupiá',
        'basin': 'Paraná',
        'river': 'Paraná',
        'status': 'Operação',
        'type': 'Natural',
        'formula': None,
        'dep_stations': None,
        've_included': True,
        'observations': None
    },
    246: {
        'name': 'Porto Primavera',
        'basin': 'Paraná',
        'river': 'Paraná',
        'status': 'Operação',
        'type': 'Natural',
        'formula': None,
        'dep_stations': None,
        've_included': True,
        'observations': None
    },
    247: {
        'name': 'Caçu',
        'basin': 'Paranaíba',
        'river': 'Claro',
        'status': 'Operação',
        'type': 'Natural',
        'formula': None,
        'dep_stations': None,
        've_included': True,
        'observations': None
    },
    248: {
        'name': 'Barra dos Coqueiros',
        'basin': 'Paranaíba',
        'river': 'Claro',
        'status': 'Operação',
        'type': 'Natural',
        'formula': None,
        'dep_stations': None,
        've_included': True,
        'observations': None
    },
    249: {
        'name': 'Ourinhos',
        'basin': 'Paranapanema',
        'river': 'Paranapanema',
        'status': 'Operação',
        'type': 'Natural',
        'formula': None,
        'dep_stations': None,
        've_included': True,
        'observations': None
    },
    251: {
        'name': 'Serra do Facão',
        'basin': 'Paranaíba',
        'river': 'São Marcos',
        'status': 'Operação',
        'type': 'Natural',
        'formula': None,
        'dep_stations': None,
        've_included': True,
        'observations': None
    },
    252: {
        'name': 'Itiquira II',
        'basin': 'Paraguai',
        'river': 'Piquiri',
        'status': 'Operação',
        'type': 'Natural',
        'formula': lambda x: x[0],
        'dep_stations': [259],
        've_included': True,
        'observations': 'Adicionado posteriormente (não se encontra no pdf)'
    },
    253: {
        'name': 'São Salvador',
        'basin': 'Tocantins',
        'river': 'Tocantins',
        'status': 'Operação',
        'type': 'Natural',
        'formula': None,
        'dep_stations': None,
        've_included': True,
        'observations': None
    },
    254: {
        'name': 'Pedra do Cavalo',
        'basin': 'Atlântico Leste',
        'river': 'Paraguaçu',
        'status': 'Operação',
        'type': 'Natural',
        'formula': None,
        'dep_stations': None,
        've_included': True,
        'observations': None
    },
    255: {
        'name': 'Irapé',
        'basin': 'Jequitinhonha',
        'river': 'Jequitinhonha',
        'status': 'Operação',
        'type': 'Natural',
        'formula': None,
        'dep_stations': None,
        've_included': True,
        'observations': None
    },
    257: {
        'name': 'Peixe Angical',
        'basin': 'Tocantins',
        'river': 'Tocantins',
        'status': 'Operação',
        'type': 'Natural',
        'formula': None,
        'dep_stations': None,
        've_included': True,
        'observations': None
    },
    259: {
        'name': 'Itiquira I',
        'basin': 'Paraguai',
        'river': 'Itiquira',
        'status': 'Operação',
        'type': 'Natural',
        'formula': None,
        'dep_stations': None,
        've_included': True,
        'observations': None
    },
    261: {
        'name': 'Foz do Rio Claro',
        'basin': 'Paranaíba',
        'river': 'Claro',
        'status': 'Operação',
        'type': 'Natural',
        'formula': None,
        'dep_stations': None,
        've_included': True,
        'observations': None
    },
    262: {
        'name': 'Guilman-Amorim',
        'basin': 'Doce',
        'river': 'Piracicaba',
        'status': 'Operação',
        'type': 'Natural',
        'formula': None,
        'dep_stations': None,
        've_included': True,
        'observations': None
    },
    263: {
        'name': 'Porto Estrela',
        'basin': 'Doce',
        'river': 'Santo Antônio',
        'status': 'Operação',
        'type': 'Natural',
        'formula': None,
        'dep_stations': None,
        've_included': True,
        'observations': None
    },
    266: {
        'name': 'Itaipu',
        'basin': 'Paraná',
        'river': 'Paraná',
        'status': 'Operação',
        'type': 'Natural',
        'formula': None,
        'dep_stations': None,
        've_included': True,
        'observations': None
    },
    269: {
        'name': 'Balbina',
        'basin': 'Amazonas',
        'river': 'Uatumã',
        'status': 'Operação',
        'type': 'Natural',
        'formula': None,
        'dep_stations': None,
        've_included': True,
        'observations': None
    },
    270: {
        'name': 'Serra da Mesa',
        'basin': 'Tocantins',
        'river': 'Tocantins',
        'status': 'Operação',
        'type': 'Natural',
        'formula': None,
        'dep_stations': None,
        've_included': True,
        'observations': None
    },
    271: {
        'name': 'Estreito Tocantins',
        'basin': 'Tocantins',
        'river': 'Tocantins',
        'status': 'Operação',
        'type': 'Natural',
        'formula': None,
        'dep_stations': None,
        've_included': True,
        'observations': None
    },
    273: {
        'name': 'Lajeado',
        'basin': 'Tocantins',
        'river': 'Tocantins',
        'status': 'Operação',
        'type': 'Natural',
        'formula': None,
        'dep_stations': None,
        've_included': True,
        'observations': None
    },
    275: {
        'name': 'Tucuruí',
        'basin': 'Tocantins',
        'river': 'Tocantins',
        'status': 'Operação',
        'type': 'Natural',
        'formula': None,
        'dep_stations': None,
        've_included': True,
        'observations': None
    },
    277: {
        'name': 'Curuá-Una',
        'basin': 'Amazonas',
        'river': 'Curuá-Una',
        'status': 'Operação',
        'type': 'Natural',
        'formula': None,
        'dep_stations': None,
        've_included': True,
        'observations': None
    },
    278: {
        'name': 'Manso',
        'basin': 'Paraguai',
        'river': 'Manso',
        'status': 'Operação',
        'type': 'Natural',
        'formula': None,
        'dep_stations': None,
        've_included': True,
        'observations': None
    },
    279: {
        'name': 'Samuel',
        'basin': 'Amazonas',
        'river': 'Jamari',
        'status': 'Operação',
        'type': 'Natural',
        'formula': None,
        'dep_stations': None,
        've_included': True,
        'observations': None
    },
    280: {
        'name': 'Coaracy Nunes',
        'basin': 'Amazonas',
        'river': 'Araguari',
        'status': 'Operação',
        'type': 'Natural',
        'formula': None,
        'dep_stations': None,
        've_included': True,
        'observations': None
    },
    281: {
        'name': 'Ponte de Pedra',
        'basin': 'Paraguai',
        'river': 'Correntes',
        'status': 'Operação',
        'type': 'Natural',
        'formula': None,
        'dep_stations': None,
        've_included': True,
        'observations': None
    },
    283: {
        'name': 'Santa Clara - MG',
        'basin': 'Mucuri',
        'river': 'Mucuri',
        'status': 'Operação',
        'type': 'Natural',
        'formula': None,
        'dep_stations': None,
        've_included': True,
        'observations': None
    },
    284: {
        'name': '14 de Julho',
        'basin': 'Jacuí',
        'river': 'Antas',
        'status': 'Operação',
        'type': 'Natural',
        'formula': None,
        'dep_stations': None,
        've_included': True,
        'observations': None
    },
    285: {
        'name': 'Jirau',
        'basin': 'Amazonas',
        'river': 'Madeira',
        'status': 'Operação',
        'type': 'Natural',
        'formula': None,
        'dep_stations': None,
        've_included': True,
        'observations': None
    },
    286: {
        'name': 'Quebra Queixo',
        'basin': 'Uruguai',
        'river': 'Chapecó',
        'status': 'Operação',
        'type': 'Natural',
        'formula': None,
        'dep_stations': None,
        've_included': True,
        'observations': None
    },
    287: {
        'name': 'Santo Antônio',
        'basin': 'Amazonas',
        'river': 'Madeira',
        'status': 'Operação',
        'type': 'Natural',
        'formula': None,
        'dep_stations': None,
        've_included': True,
        'observations': None
    },
    288: {
        'name': 'Belo Monte',
        'basin': 'Amazonas',
        'river': 'Xingu',
        'status': 'Operação',
        'type': 'Natural',
        'formula': None,
        'dep_stations': None,
        've_included': True,
        'observations': None
    },
    290: {
        'name': 'Santo Antônio do Jari',
        'basin': 'Amazonas',
        'river': 'Jari',
        'status': 'Operação',
        'type': 'Natural',
        'formula': None,
        'dep_stations': None,
        've_included': True,
        'observations': None
    },
    291: {
        'name': 'Dardanelos',
        'basin': 'Amazonas',
        'river': 'Aripuanã',
        'status': 'Operação',
        'type': 'Natural',
        'formula': None,
        'dep_stations': None,
        've_included': True,
        'observations': None
    },
    292: {
        'name': 'Belo Monte Principal',
        'basin': 'Amazonas',
        'river': 'Xingu',
        'status': 'Operação',

        'type': 'Artificial',
        'formula': lambda x, m: x[0].apply(lambda y: ((y - hydrogram_used[m], 13900)
                                                      [y > hydrogram_used[m] + 13900], 0)
                                                      [y < hydrogram_used[m]]),
        'dep_stations': [288],
        've_included': False,
        'observations': None
    },
    294: {
        'name': 'Salto',
        'basin': 'Paranaíba',
        'river': 'Verde',
        'status': 'Operação',
        'type': 'Natural',
        'formula': None,
        'dep_stations': None,
        've_included': True,
        'observations': None
    },
    295: {
        'name': 'Jauru',
        'basin': 'Paraguai',
        'river': 'Jauru',
        'status': 'Operação',
        'type': 'Natural',
        'formula': None,
        'dep_stations': None,
        've_included': True,
        'observations': None
    },
    296: {
        'name': 'Guaporé',
        'basin': 'Amazonas',
        'river': 'Guaporé',
        'status': 'Operação',
        'type': 'Natural',
        'formula': None,
        'dep_stations': None,
        've_included': True,
        'observations': None
    },
    297: {
        'name': 'Ferreira Gomes',
        'basin': 'Amazonas',
        'river': 'Araguari',
        'status': 'Operação',
        'type': 'Natural',
        'formula': None,
        'dep_stations': None,
        've_included': True,
        'observations': None
    },
    298: {
        'name': 'Santa Cecília Bombeamento',
        'basin': 'Paraíba do Sul',
        'river': 'Paraíba do Sul',
        'status': 'Operação',
        'type': 'Artificial',
        'formula': lambda x: x[0].apply(lambda y: (((y * (119 / 190), 119)[190 < y <= 209], y - 90)[209 < y <= 250], 160)[y > 250]),
        'dep_stations': [125],
        've_included': False,
        'observations': 'Bombeamento em Santa Cecília'
    },
    299: {
        'name': 'Ilha dos Pombos',
        'basin': 'Paraíba do Sul',
        'river': 'Paraíba do Sul',
        'status': 'Operação',
        'type': 'Artificial',
        'formula': lambda x: x[0] - x[1] - x[2] + x[3],
        'dep_stations': [130, 298, 203, 304],
        've_included': False,
        'observations': 'Bombeamento em Santa Cecília'
    },
    # 300: {
    #     'name': 'Posto Nulo',
    #     'basin': None,
    #     'river': None,
    #     'status': 'Operação',
    #     'type': 'Natural',
    #     'formula': None,
    #     'dep_stations': None,
    #     've_included': False,
    #     'observations': 'Série nula para postos onde originalmente não existia vazão'
    # },
    302: {
        'name': 'Pimental Artificial',
        'basin': 'Amazonas',
        'river': 'Xingu',
        'status': 'Operação',
        'type': 'Artificial',
        'formula': lambda x: x[0] - x[1],
        'dep_stations': [288, 292],
        've_included': False,
        'observations': None
    },
    303: {
        'name': 'Fontes',
        'basin': 'Paraíba do Sul',
        'river': 'Ribeirão das Lajes',
        'status': 'Operação',
        'type': 'Artificial',
        'formula': lambda x: x[0].apply(lambda y: (17, y)[y < 17]) + (x[1] - x[2]).apply(lambda z: min(z, 34)),
        'dep_stations': [132, 316, 131],
        've_included': False,
        'observations': None
    },
    304: {
        'name': 'Santana Vertimento',
        'basin': 'Paraíba do Sul',
        'river': 'Piraí',
        'status': 'Operação',
        'type': 'Artificial',
        'formula': lambda x: x[0] - x[1],
        'dep_stations': [315, 316],
        've_included': False,
        'observations': None
    },
    306: {
        'name': 'Pereira Passos',
        'basin': 'Paraíba do Sul',
        'river': 'Ribeirão das Lajes',
        'status': 'Operação',
        'type': 'Artificial',
        'formula': lambda x: x[0] + x[1],
        'dep_stations': [303, 131],
        've_included': False,
        'observations': 'Acréscimo de Nilo Peçanha'
    },
    # 314: {
    #     'name': 'Itaocara',
    #     'basin': 'Paraíba do Sul',
    #     'river': 'Paraíba do Sul',
    #     'status': 'Operação',
    #     'type': 'Artificial',
    #     'formula': lambda x: x[0] - x[1] - x[2] + x[3],
    #     'dep_stations': [199, 298, 203, 304],
    #     've_included': False,
    #     'observations': 'Desconto do bombeamento em Santa Cecília e acréscimo de vertimento de Santana'
    # },
    315: {
        'name': 'Santana',
        'basin': 'Paraíba do Sul',
        'river': 'Ribeirão das Lajes',
        'status': 'Operação',
        'type': 'Artificial',
        'formula': lambda x: x[0] - x[1] + x[2] + x[3],
        'dep_stations': [203, 201, 317, 298],
        've_included': False,
        'observations': None
    },
    316: {
        'name': 'Vigário',
        'basin': 'Paraíba do Sul',
        'river': 'Ribeirão das Lajes',
        'status': 'Operação',
        'type': 'Artificial',
        'formula': lambda x: x[0].apply(lambda y: min(y, 190)),
        'dep_stations': [315],
        've_included': False,
        'observations': None
    },
    317: {
        'name': 'Tocos Vertimento',
        'basin': 'Paraíba do Sul',
        'river': 'Piraí',
        'status': 'Operação',
        'type': 'Artificial',
        'formula': lambda x: x[0].apply(lambda y: max(0, y - 25)),
        'dep_stations': [201],
        've_included': False,
        'observations': 'Vazão restante no rio Piraí após desvio para Lajes'
    },
    318: {
        'name': 'Henry Borden',
        'basin': 'Atlântico Sudeste',
        'river': 'Cubatão',
        'status': 'Operação',
        'type': 'Artificial',
        'formula': lambda x: x[0] + x[1] + x[2] + 0.1 * (x[3] - x[1] - x[2]),
        'dep_stations': [116, 117, 118, 161],
        've_included': False,
        'observations': 'Vazão disponível em H. Borden contabilizando o possível de ser bombeado no Tietê e as retiradas'
                        'para abastecimento nos reservatórios de Guarapiranga e Billings'
    },
    319: {
        'name': 'Billings',
        'basin': 'Tietê',
        'river': 'Pinheiros',
        'status': 'Operação',
        'type': 'Artificial',
        'formula': lambda x: x[0] + x[1] + 0.1 * (x[2] - x[0] - x[1]),
        'dep_stations': [117, 118, 161],
        've_included': False,
        'observations': 'Vazão desviada para H. Borden contabilizando o possível de ser bombeado no Tietê e as retiradas'
                        'para abastecimento nos reservatórios de Guarapiranga e Billings'
    },
    166: {
        'name': 'REE Itaipu',
        'basin': 'Parana',
        'river': None,
        'status': None,
        'type': 'Artificial',
        'formula': lambda x: x[0] + x[1] - x[2] - x[3] - x[4],
        'dep_stations': [266, 154, 34, 243, 61],
        've_included': True,
        'observations': 'Arquivo 166 no site do ONS'
    },
    301: {
        'name': 'Billings Antiga',
        'basin': 'Tietê',
        'river': 'Pinheiros',
        'status': 'Operação',
        'type': 'Natural',
        'formula': None,
        'dep_stations': None,
        've_included': True,
        'observations': 'Adicionado posteriormente (não se encontra no pdf)'
    },
    320: {
        'name': 'Billings Pedras',
        'basin': 'Tietê',
        'river': 'Pinheiros',
        'status': 'Operação',
        'type': 'Natural',
        'formula': None,
        'dep_stations': None,
        've_included': True,
        'observations': 'Adicionado posteriormente (não se encontra no pdf)'
    },
    921: {
        'name': 'Tocos_Lajes',
        'basin': 'Paraíba do Sul',
        'river': 'Piraí',
        'status': 'Operação',
        'type': 'Artificial',
        'formula': lambda x: x[0] + x[1],
        'dep_stations': [201, 202],
        've_included': False,
    },
}

incremental_stations = {
    34: {
        'name': 'Ilha Solteira',
        'formula_nat_inc': lambda x: x[0] - x[1] - x[2] - x[3] - x[4] - x[5],
        'formula_inc_nat': lambda x: x[0] + x[1] + x[2] + x[3] + x[4] + x[5],
        'dep_stations': [34, 33, 18, 99, 241, 261],
        'traveltime_natural': [0, 30, 18, 46, 28, 28],
        'traveltime_reserv': [0, 14, 6, 18, 9, 10],
        'type': 'Aggregate-Tiete',
    },
    238: {
        'name': 'Bariri',
        'formula_nat_inc': lambda x: x[0] - x[1],
        'formula_inc_nat': lambda x: x[0] + x[1],
        'dep_stations': [238, 237],
        'type': 'Dist. Incremental',
    },
    239: {
        'name': 'Ibitinga',
        'formula_nat_inc': lambda x: x[0] - x[1],
        'formula_inc_nat': lambda x: x[0] + x[1],
        'dep_stations': [239, 238],
        'traveltime_natural': [0, 24],
        'traveltime_reserv': [0, 18],
        'type': 'Aggregate-Tiete',
    },
    240: {
        'name': 'Promissão',
        'formula_nat_inc': lambda x: x[0] - x[1],
        'formula_inc_nat': lambda x: x[0] + x[1],
        'dep_stations': [240, 239],
        'type': 'Dist. Incremental',
    },
    242: {
        'name': 'Nova Avanhandava',
        'formula_nat_inc': lambda x: x[0] - x[1],
        'formula_inc_nat': lambda x: x[0] + x[1],
        'dep_stations': [242, 240],
        'traveltime_natural': [0, 42],
        'traveltime_reserv': [0, 12],
        'type': 'Aggregate-Tiete',
    },
    243: {
        'name': 'Três Irmãos',
        'formula_nat_inc': lambda x: x[0] - x[1],
        'formula_inc_nat': lambda x: x[0] + x[1],
        'dep_stations': [243, 242],
        'traveltime_natural': [0, 42],
        'traveltime_reserv': [0, 7],
        'type': 'Aggregate-Tiete',
    },
    245: {
        'name': 'Jupiá',
        'formula_nat_inc': lambda x: x[0] - x[1] - x[2],
        'formula_inc_nat': lambda x: x[0] + x[1] + x[2],
        'dep_stations': [245, 34, 243],
        'traveltime_natural': [0, 5, 7],
        'traveltime_reserv': [0, 3, 5],
        'type': 'Aggregate-Tiete',
    },
    246: {
        'name': 'Porto Primavera',
        'formula_nat_inc': lambda x: x[0] - x[1] - x[2],
        'formula_inc_nat': lambda x: x[0] + x[1] + x[2],
        'dep_stations': [246, 245, 154],
        'traveltime_natural': [0, 48, 32],
        'traveltime_reserv': [0, 24, 20],
        'type': 'Aggregate-Tiete',
    },
    266: {
        'name': 'Itaipu',
        'formula_nat_inc': lambda x: x[0] - x[1] - x[2],
        'formula_inc_nat': lambda x: x[0] + x[1] + x[2],
        'dep_stations': [266, 63, 246],
        'traveltime_natural': [0, 48, 48],
        'traveltime_reserv': [0, 48, 48],
        'type': 'Aggregate-Tiete',
    },
    191: {
        'name': 'Cana Brava',
        'formula_nat_inc': lambda x: x[0] - x[1],
        'formula_inc_nat': lambda x: x[0] + x[1],
        'dep_stations': [191, 270],
        'type': 'Dist. Incremental',
    },
    253: {
        'name': 'São Salvador',
        'formula_nat_inc': lambda x: x[0] - x[1],
        'formula_inc_nat': lambda x: x[0] + x[1],
        'dep_stations': [253, 191],
        'type': 'Dist. Incremental',
    },
    257: {
        'name': 'Peixe Angical',
        'formula_nat_inc': lambda x: x[0] - x[1],
        'formula_inc_nat': lambda x: x[0] + x[1],
        'dep_stations': [257, 253],
        'type': 'Dist. Incremental',
    },
    273: {
        'name': 'Lajeado',
        'formula_nat_inc': lambda x: x[0] - x[1],
        'formula_inc_nat': lambda x: x[0] + x[1],
        'dep_stations': [273, 257],
        'type': 'Dist. Incremental',
    },
}

# Dictionary containing the formulae for the special stations
special_stations = {
    109: {
        'name': 'Pedreira',
        'type': 'Aggregate-Tiete',
        'formula': lambda x: x[0],
        'dep_stations': [118],
    },
    104: {
        'name': 'Traição',
        'type': 'Aggregate-Tiete',
        'formula': lambda x: x[0] + x[1],
        'dep_stations': [117, 118],
    },
    116: {
        'name': 'Pedras',
        'type': 'Aggregate-Tiete',
        'formula': lambda x: x[0] - x[1],
        'dep_stations': [119, 118],
    },
    # region Remover depois
    # 246: {
    #     'name': 'P. Primavera',
    #     'type': 'Aggregate-Tiete',
    #     'formula': lambda x: x[0] * 0.603,
    #     'dep_stations': [245],
    # },
    # endregion
    # 154: {
    #     'name': 'São Domingos',
    #     'type': 'Dist. Incremental',
    #     'formula': lambda x: x[0] * 0.179,
    #     'dep_stations': [246],
    # },
    238: {
        'name': 'Bariri Inc.',
        'type': 'Dist. Incremental',
        'formula': lambda x: x[0] * 0.342,
        'dep_stations': [239],
    },
    239: {
        'name': 'Ibitinga Inc.',
        'type': 'Dist. Incremental',
        'formula': lambda x: x[0] * 0.658,
        'dep_stations': [239],
    },
    240: {
        'name': 'Promissão Inc.',
        'type': 'Dist. Incremental',
        'formula': lambda x: x[0] * 0.717,
        'dep_stations': [242],
    },
    242: {
        'name': 'N.Avanhandava Inc.',
        'type': 'Dist. Incremental',
        'formula': lambda x: x[0] * 0.283,
        'dep_stations': [242],
    },
    191: {
        'name': 'Cana Brava Inc.',
        'type': 'Dist. Incremental',
        'formula': lambda x: x[0] * 0.504,
        'dep_stations': [253],
    },
    253: {
        'name': 'São Salvador Inc.',
        'type': 'Dist. Incremental',
        'formula': lambda x: x[0] * 0.496,
        'dep_stations': [253],
    },
    257: {
        'name': 'Peixe Angical Inc.',
        'type': 'Dist. Incremental',
        'formula': lambda x: x[0] * 0.488,
        'dep_stations': [273],
    },
    273: {
        'name': 'Lajeado Inc.',
        'type': 'Dist. Incremental',
        'formula': lambda x: x[0] * 0.512,
        'dep_stations': [273],
    },
    169: {
        'name': 'Sobradinho',
        'type': 'São Francisco',
        'formula': lambda x: x[0] + x[1] + x[2],
        'delay_time': [0, -2, -2],
        'dep_stations': [168, 156, 158],
    },
    172: {
        'name': 'Itaparica',
        'type': 'Aggregate-SF',
        'formula': lambda x: x[0],
        'dep_stations': [169],
    },
    173: {
        'name': 'Moxotó',
        'type': 'Aggregate-SF',
        'formula': lambda x: x[0],
        'delay_time': [0],
        'dep_stations': [169],
    },
    175: {
        'name': 'P. Afonso 4',
        'type': 'Aggregate-SF',
        'formula': lambda x: x[0],
        'delay_time': [0],
        'dep_stations': [169],
    },
    176: {
        'name': 'Comp. Moxotó',
        'type': 'Aggregate-SF',
        'formula': lambda x: x[0],
        'delay_time': [0],
        'dep_stations': [169],
    },
    178: {
        'name': 'Comp. Moxotó',
        'type': 'Aggregate-SF',
        'formula': lambda x: x[0],
        'delay_time': [0],
        'dep_stations': [169],
    },
    171: {
        'name': 'Itaparica Inc.',
        'type': 'Zeros',
    }
}

calculated_stations_acomph = {
    2: {
        'name': 'Itutinga',
        'type': 'calculated',
        'formula': lambda x: x[0],
        'dep_stations': [1],
    },
    104: {
        'name': 'Traição',
        'type': 'calculated',
        'formula': lambda x: x[0] + x[1],
        'dep_stations': [117, 118],
    },
    109: {
        'name': 'Pedreira',
        'type': 'calculated',
        'formula': lambda x: x[0],
        'dep_stations': [118],
    },
    119: {
        'name': 'Bill. + Pedras',
        'type': 'regressed_reverse',
        'formula': lambda x, a0, a1: a0 + a1*x[0],
        'dep_stations': [118],
    },
    116: {
        'name': 'Pedras',
        'type': 'calculated',
        'formula': lambda x: x[0] - x[1],
        'dep_stations': [119, 118],
    },
    298: {
        'name': 'Santa Cecília Bombeamento',
        'type': 'calculated',
        'formula': lambda x: x[0].apply(lambda y: (((y * (119 / 190), 119)[190 < y <= 209], y - 90)[209 < y <= 250], 160)[y > 250]),
        'dep_stations': [125],
    },
    317: {
        'name': 'Tocos Vertimento',
        'type': 'calculated',
        'formula': lambda x: x[0].apply(lambda y: max(0, y - 25)),
        'dep_stations': [201],
    },
    203: {
        'name': 'Santana',
        'type': 'regressed',
        'formula': lambda x, a0, a1: a0 + a1*x[0],
        'dep_stations': [201],
    },
    315: {
        'name': 'Santana',
        'type': 'calculated',
        'formula': lambda x: x[0] - x[1] + x[2] + x[3],
        'dep_stations': [203, 201, 317, 298],
    },
    316: {
        'name': 'Vigário',
        'type': 'calculated',
        'formula': lambda x: x[0].apply(lambda y: min(y, 190)),
        'dep_stations': [315],
    },
    304: {
        'name': 'Santana Vertimento',
        'type': 'calculated',
        'formula': lambda x: x[0] - x[1],
        'dep_stations': [315, 316],
    },
    127: {
        'name': 'Anta',
         'type': 'calculated',
         'formula': lambda x: x[0] - x[1] - x[2] + x[3],
         'dep_stations': [129, 298, 203, 304],
    },
    126: {
         'name': 'Simplício',
         'type': 'calculated',
         'formula': lambda x: x[0].apply(lambda y: (max(0, y - 90), 340)[y >= 430]),
         'dep_stations': [127],
    },
    131: {
        'name': 'Nilo Peçanha',
        'type': 'calculated',
        'formula': lambda x: x[0].apply(lambda y: min(y, 144)),
        'dep_stations': [316],
    },
    160: {
        'name': 'Ponte Nova',
        'type': 'calculated',
        'formula': lambda x: x[0]*(320/(4844-681-700)),
        'dep_stations': [161],
    },
    164: {
        'name': 'E. Souza',
        'type': 'calculated',
        'formula': lambda x: x[0] - x[1] - x[2],
        'dep_stations': [161, 117, 118],
    },
    174: {
         'name': 'P.A.123',
         'type': 'calculated',
         'formula': lambda x: x[0],
         'dep_stations': [173],
    },
    175: {
          'name': 'P.A.4',
          'type': 'calculated',
          'formula': lambda x: x[0],
          'dep_stations': [173],
    },
    292: {
          'name': 'Belo Monte Principal',
          'type': 'belo_monte',
          'formula': lambda x, m: x[0].apply(lambda y: ((y - hydrogram_used[m], 13900)
                                                      [y > hydrogram_used[m] + 13900], 0)[y < hydrogram_used[m]]),
          'dep_stations': [288],
    },
    132: {
        'name': 'Lajes',
        'type': 'calculated',
        'formula': lambda x: x[0] + x[1].apply(lambda y: min(y, 25)),
        'dep_stations': [202, 201],
    },
    303: {
        'name': 'Fontes',
        'type': 'calculated',
        'formula': lambda x: x[0].apply(lambda y: (17, y)[y < 17]) + (x[1] - x[2]).apply(lambda z: min(z, 34)),
        'dep_stations': [132, 316, 131],
    },
    306: {
        'name': 'Pereira Passos',
        'type': 'calculated',
        'formula': lambda x: x[0] + x[1],
        'dep_stations': [303, 131],
    },
    318: {
        'name': 'Henry Borden',
        'type': 'calculated',
        'formula': lambda x: x[0] + x[1] + x[2] + 0.1 * (x[3] - x[1] - x[2]),
        'dep_stations': [116, 117, 118, 161],
    },

    921: {
        'name': 'Tocos_Lajes',
        'type': 'São Francisco',
        'formula': lambda x: x[0] + x[1],
#        'delay_time': [0, -2, -2],
        'dep_stations': [201, 202],
    },
}

# Dicitionay containing the MLT (mean long term) of Ena (Natural Energy Inflow) for each submarket
# mudança na MLT
#mlt_submarkets = {'Sudeste': [65674, 70494, 68928, 54727, 39959, 32617, 25693, 20579, 19727, 23655, 31440, 48008],
#                  'Sul': [7577, 8336, 7120, 6594, 8634, 10504, 10938, 9999, 11702, 13351, 9426, 7453],
#                  'Nordeste': [13565, 14252, 14134, 11546, 6987, 4614, 3805, 3319, 2966, 3233, 5297, 9873],
#                  'Norte': [15657, 22694, 26673, 26996, 20401, 10698, 5278, 3215, 2288, 2402, 4029, 8297]
#                  }
mlt_submarkets = {'Sudeste': [65805, 70900, 69326, 54954, 40060, 32662, 25728, 20616, 19716, 23606, 31431, 48039],
                  'Sul': [7474, 8215, 7010, 6483, 8494, 10387, 10887, 9929, 11549, 13135, 9270, 7390],
                  'Nordeste': [13512, 14256, 14160, 11574, 6988, 4611, 3799, 3314, 2959, 3224, 5303, 9837],
                  'Norte': [15597, 22630, 26690, 27001, 20391, 10664, 5246, 3189, 2274, 2390, 4029, 8271]
                  }
